export const RENTALS_FETCH_ALL_RENTALS_SUCCESS =
  'RENTALS_FETCH_ALL_RENTALS_SUCCESS';
export const RENTALS_FETCH_ALL_RENTALS_PENDING =
  'RENTALS_FETCH_ALL_RENTALS_PENDING';
export const RENTALS_FETCH_ALL_RENTALS_ERROR =
  'RENTALS_FETCH_ALL_RENTALS_ERROR';
