export const RENTAL_FETCH_RENTAL_BY_ID_PENDING =
  'RENTAL_FETCH_RENTAL_BY_ID_PENDING';
export const RENTAL_FETCH_RENTAL_BY_ID_SUCCESS =
  'RENTAL_FETCH_RENTAL_BY_ID_SUCCESS';
export const RENTAL_FETCH_RENTAL_ERROR = 'RENTAL_FETCH_RENTAL_ERROR';
